### ISSUE TITLE
What information to track about contributors

### ISSUE THREAD

**Issue by twitwi** [swcarpentry/swc-releases#3]
Currently the repository mainly contains a list of author names.
Zenodo also allows for attribution and ORCID.

My current point of view:
- attributions evolve and might be costly maintain (keeping track of authors is already painful),
- ORCID, if made optional, is valuable to have robust attribution,
 
As such we could maintain a name-or-email->ORCID mapping and use it for the release on zenodo.

**Comment by tracykteal** [comment]
+1 to ORCID

Agree that including affiliation is a lot of work to get correct without much added benefit.

**Comment by k8hertweck** [comment]
I'd like to try collecting some of this information for the next lesson release. I don't believe we track ORCID in AMY, so I think the easiest way to test it out is to create a Google Form that asks for name, GitHub ID, and ORCID. Anything else?

**Comment by twitwi** [comment]
maybe: if they have old contributions for which they want to opt out of being listed as contributors (we could store today as an opt-out date, so that they re-appear if they re-contribute).

**Comment by k8hertweck** [comment]
That would require a date on a lesson-by-lesson basis. I'd be more inclined to require resubmitting the form, or contacting someone (me?) individually to update the form.

**Comment by twitwi** [comment]
You're right, the opt-out is less important and could be announced in the mail inviting to provide ORCID, but handled via a reply to you.

**Comment by twitwi** [comment]
btw, we could use the email to encourage people to get an ORCID

**Comment by k8hertweck** [comment]
Yes, I like including the PSA. I always assume folks know about ORCID, but am surprised about how frequently folks haven't heard of it.

**Comment by jduckles** [comment]
FYI: Blog post from @k8hertweck on this was just merged.

**Comment by twitwi** [comment]
So, for now, we're tracking:
- preferred name (for the release)
- opt-out list to not appear as author (for the release)
- ORCID (for zenodo)
- email**s** used in any commit (only for the .mailmap)

I'm closing this issue.
