### ISSUE TITLE
Jekyll pages not building due to branches/tags that disappeared

### ISSUE THREAD

**Issue by twitwi** [swcarpentry/swc-releases#6]
Here are the failing checks.

CHECKING: 2016.06/instructor-training
 - testing url: https://github.com/swcarpentry/instructor-training/tree/2016.06
 - NB by @twitwi: the branch has been deleted

CHECKING: 2017.02/lesson-example
 - testing url: https://github.com/swcarpentry/lesson-example/tree/2017.02
 - NB by @twitwi: it seems it was a branch, which was bad as this repo is "imported" via github and having branches is confusing. So it is right that it has been deleted, and we should create a 2017.02 tag instead.

CHECKING: 2016.06/workshop-template
 - testing url: https://github.com/swcarpentry/workshop-template/tree/2016.06
 - NB by @twitwi: the tag seems to have been renamed from 2016.06 to 2016-06 (dot to dash)

CHECKING: 2017.02/workshop-template
 - testing url: https://github.com/swcarpentry/workshop-template/tree/2017.02
 - NB by @twitwi: the tag seems to have been renamed from 2017.02 to 2017-02 (dot to dash)

**Comment by twitwi** [comment]
@rgaiacs I know you have a good overview of what happens in the project, would you know something about these points? or do you know how to "github blame" for deleting branches?

**Comment by rgaiacs** [comment]
You can use http://lists.software-carpentry.org/pipermail/maintainers/2017-March/000357.html to blame me.

**Comment by twitwi** [comment]
@rgaiacs that was the right thing to do given how github import works.

Is is ok if I (or anyone) rename the `workshop-template` tags to their version with a dot?
If so, I will also create the tag on the `lesson-example` repo.

Do you know anything about the first point (`instructor-training`)?

**Comment by rgaiacs** [comment]
> Is is ok if I (or anyone) rename the workshop-template tags to their version with a dot?

It is OK.

> If so, I will also create the tag on the lesson-example repo.

Thanks.

> Do you know anything about the first point (instructor-training)?

I don't know how to get information to blame anyone. But I have

~~~
$ git log -1 remotes/origin/2016.06
commit 8ddff61d6e68e572bf4ffef980994941e74163cf (origin/2016.06)
Author: Rémi Emonet <remi.emonet@reverse--com.heeere>
Date:   Tue Jul 19 12:36:19 2016 +0200

    [DOI: 10.5281/zenodo.57571] Added version (2016.06) to all pages via CSS
$ git log -1 remotes/origin/2017.02
commit d263d4bde72d223da440a0c1528ed0d5e8c3d063 (origin/2017.02)
Author: Rémi Emonet <remi.emonet@reverse--com.heeere>
Date:   Wed Feb 8 23:53:32 2017 +0100

    [DOI: 10.5281/zenodo.278229] Added version (2017.02) to all pages via CSS
~~~

Could you use that information to create the tag?

Sorry for all the trouble that I create.

**Comment by twitwi** [comment]
Thanks for the info, I should be able to push all tags with that.

And, there is no trouble.
Thanks for all the things you're doing.

**Comment by twitwi** [comment]
all done, everything seems ok
